apiVersion: v1
kind: LimitRange
metadata:
   name: testlimitrange
spec:
  limits:
  - default:
      cpu: 600m
      memory: 100Mi
    defaultRequest:
      cpu: 100m
      memory: 50Mi
    max:
      cpu: 1000m
      memory: 500Mi
    min:
      cpu: 10m
      memory: 10Mi
    type: Container
