[bharath@bharath k8spractise]$ kubectl create -f bkdeployments.yml
deployment.extensions "bharath-deploy" created
[bharath@bharath k8spractise]$ kubectl get deploy
NAME             DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
bharath-deploy   10        10        10           0           6s
[bharath@bharath k8spractise]$


[bharath@bharath k8spractise]$ kubectl describe deploy bharath-deploy
Name:                   bharath-deploy
Namespace:              default
CreationTimestamp:      Sat, 02 Jun 2018 16:40:13 +0200
Labels:                 app=hellobkraju
Annotations:            deployment.kubernetes.io/revision=2
                        kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"kubernetes.io/change-cause":"kubectl apply --filename=bkdeployments....
                        kubernetes.io/change-cause=kubectl apply --filename=bkdeployments.yml --record=true
Selector:               app=hellobkraju
Replicas:               10 desired | 10 updated | 10 total | 10 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        10
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:  app=hellobkraju
  Containers:
   hello-raju-deployment:
    Image:        nigelpoulton/pluralsight-docker-ci:edge
    Port:         8080/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   bharath-deploy-6b55fdc85c (10/10 replicas created)
Events:          <none>
[bharath@bharath k8spractise]$

